### ISSUE TITLE
Feature Request: Change twad's working directory to WAD Dir

### ISSUE THREAD

**Issue by nullstalgia** [zmnpl/twad#1]
~~Ooh, first issue?~~

As someone who likes to try a lot of mods, I run into issues with config files being conflicting or whatever. So what I do is I have a good config file that I duplicate for every big mod (like Brutal Doom vs Project Brutality vs... other mod names i cant remember.), and then load it when I play with that mod on most maps.

![image](https://user-images.githubusercontent.com/20761757/98882349-e72e2500-2440-11eb-86eb-c1956ac0d261.png)

But when I have `-config brutal.ini` for example, it saves it to `/home/tony/`, not where it sets DOOMWADDIR.

(Honestly, even better would be to have a WAD Dir and a Config Dir that is selectable like the IWAD and Source Port. I could try to add it/start a new feature request, but I don't know if you think it's feature bloat. I might try, but I haven't used golang in ages.)

**Comment by nullstalgia** [comment]
Right, well, turns out it might not be possible due to conflicts with boom compatibility. However, in the pull request, I think I have a solution for this: give it the full path of $DOOMWADDIR (is actually cfg waddir)+"/config/+config_name.

**Comment by zmnpl** [comment]
Hey man, very sorry for the long delay. I really have missed your Issue/PR and am not sure how that went unnoticed for so long. I'll look into your suggestions later on the day. I guess I wasn't prepared that someone would actually contribute to the project, but I will be stoked if I can still merge in your suggestions!

**Comment by zmnpl** [comment]
As stated in your PR I would have (and have) done a couple of things differently...

There are two different options
1) Use game exclusive config
Can be done by ticking a checkbox Add/Edit dialog. twad will take care for storage location and name. Configs are stored in ~/.config/twad/configs
2) Use a shared config. Done by providing a name in the Add/Edit dialog. twad automatically adds the correct file extension if not given. Shared configs are stored in ~/.config/twad/configs_shared/$port_name

- To avoid conflicts / weird behaviour I store configs for different source ports in different subfolders
- Instead of maintaining config file names in the json I show the config files listed from their storage directory
- Autocompletion when entering a shared config name based on existing ones

I've build in the feature as described above. Please have a look and let me know what you think!

**Comment by zmnpl** [comment]
Going to close here, but don't hesitate to reopen an issue. Again thanks for the constructive feedback!
