### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by philthespookykitten** [zmnpl/twad#3]
Hi there, I love your terminal launcher and it is ideal for my usage but I do have a couple of questions and not sure if I'm being dumb, or if they are just not implemented in the code.

Firstly, is there anyway to remove a mod to a game once added? At the moment I have to delete and then reedit the game which seems rather inefficient.

Secondly, using the idgamesbrowser it will download the files just fine but I have to manually unzip the files that it downloads in order to use the .wad that lies within. Is there anyway twad will unzip that automatically for me?

Anyway, I really do like your launcher as have been looking for something like this on/off for a couple of years before stumbling across it on the AUR.

**Comment by zmnpl** [comment]
Hi, so I really feel dumb to answer after almost a year. Not sure why I haven't seen this but yeah ... my apologies. If you still want the answers, here they are :)

To remove a mod from a game you can:
- Navigate to the game
- Press TAB to switch your focus over to the mods list
- Press DEL
- Confirm (To switch choices use TAB again)

To the second question: 
Right now there is no auto-unzip. I was hesitant to do it because zip-files can be malicious and doing it without explicit user consent might be dangerous.
But, there is an "import" for zip files within twad via F3. There you can select a zip from your file system and name the sub-folder. Twad will import it into your set DOOMWADDIR and give it the name you chose. I've just spun this up myself and I think it would be nice if the selection would start in the DOOMWADDIR and not just "/" so I'll look into that again.

Hope twad still works well for you.

Best regards

**Comment by philthespookykitten** [comment]
All good mate. I certainly understand real life can get in the way of our little side projects.

Tab....of course! So obvious now that I see it. I swear I tried everything on the keyboard but apparently not :P

I can see your point with not wanting to auto-unzip due to security concerns. I did not realize there was an import function so if I did download something from the idgames browser then I would switch to a terminal, unzip in the DOOMWADDIR and then head back into twad which was pretty clunky to be frank. It is honestly still a little bit clunky with your F3 option although starting the import selection from DOOMWADDIR would certainly help there. Still in my ideal world there would be a keyboard shortcut that auto expands the most recent download from the idgames browser, perhaps with a prompt explaining the security risks and confirmation that you accept the risks.

Cheers for the reply. Look forward to your response in 2023!

And yes, I'm still using twad off an on so thanks for the utility, its great for someone who prefers to live in the terminal when I can.

**Comment by zmnpl** [comment]
*It's 2023*

So I took this as an opportunity and build in the following:
Now, when you download something from IDGames twad will, immediately after the download, suggest to import the just downloaded archive and even suggest the directory name within DOOMWADDIR to be the IDGames game title.

Hope that helps :)

Was fun to do something in the project again anyways!

**Comment by philthespookykitten** [comment]
That was a great update thanks! It makes the IDGames Browser much more usable. Glad you had fun indulging me! I have bugs and other feature requests if you want other 'fun' things to do with this project again if you want. :p

**Comment by zmnpl** [comment]
Bring'em on. Will not promise anything before 2024 though.

I'll close this one then.
