### ISSUE TITLE
Passing "Others" parameters with spaces

### ISSUE THREAD

**Issue by Sneethe** [zmnpl/twad#6]
When loading any type of file through the "Others" field. If the path to the file has any spaces, it will not load the file. Neither escaping the spaces with \ ,nor wrapping the file path in quotes has any effect. 

So far I've observed this behavior upon loading configs and patch files.
This is inconsistent with how twad loads mods, as spaces in file names don't impact functionality. 
Perhaps this is related but when any filename provided through the "Others" field. It has to be the full path name (without spaces present). Again inconsistent with the $DOOMWADDIR being the CWD that we see when loading in our mods.

I'm running v0.20.0 binary

**Comment by zmnpl** [comment]
Hey, first off sorry for the very delayed answer :)

In case you are still interested I've looked into the issue and this is indeed a good catch. I think I've fixed this with this commit:
https://github.com/zmnpl/twad/commit/bb5b329be2710c085446c22a7c1d43329e42b427

Basically I did not consider "others" being used that extensively and only thought about engine parameters which don't contain spaces. I took the naive route and just split by space which obviously does not work for your use case. I now treat the "other" parameters as one-record-csv where the field separator is a space. That means you can now quote your string with double quotes if it contains spaces and that should work.

Regarding the issue, that you need to provide the absolute path: I cannot reproduce that one. Check out the two attached screenshots where I tried to replicate the issue. The configuration for Scythe II works like that, with the relative path to DOOMWADDIR.
Though, I am testing that now that the first issue is fixed so that might have been the reason. Please give it a shot :)

Edit:
Now that I thought about it... DOOMAWADDIR is not the CWD as you phrase it. It really is just set as environment variable. All the source ports look for the variable and if it is set, wads (and pk3 and so on) are searched there. Seems like ports don't look for configs or other file types in DOOMWADDIR. So that is port behaviour.
It might be possible to add an option to use DOOMWADDIR as working dir, though not sure what unwanted effects that might have.

![scythe2_modasothers](https://github.com/zmnpl/twad/assets/9001667/f775903d-1f19-474c-b044-a7f363553de7)
![scythe2_nomods](https://github.com/zmnpl/twad/assets/9001667/4b2fd322-b4d3-4b2b-a64f-28f239cfa206)
